### Lagrange interpolation approach

Consider gate $U(x) = e^{-ixG}$

$G$ has $n$ distinguish eigenvalues $\lambda_k, k=\{0,1,...,n-1\}$

$e^{-i x \boldsymbol{G}}=\sum_{k=0}^{n-1} e^{-i x \lambda_{k}} \prod_{l=0, l \neq k}^{n-1} \frac{\boldsymbol{G}-\lambda_{l} \boldsymbol{I}}{\lambda_{k}-\lambda_{l}} = f(\boldsymbol{G})=\Lambda_0 I + \Lambda_1 G + ... + \Lambda_{n-1} G^{n - 1}$

#### 1. Calculate coeff ${\Lambda_i}$ of a gate

Here we treat $\boldsymbol{G}$ as a variable. The input is only x and eigenvalues ${\lambda_i}$

In [1]:
import numpy as np
import base
# Input
x = -np.pi / 2
lambdas = [-5/2, -3/2, -1/2, 1/2, 3/2, 5/2]
# Polynomial presentation
fG = base.calculate_Lambda(lambdas, x)
# Output
print("Lambda_i: ", fG.coeff)

Lambda_i:  [(0.9501747372194234+1.214306433183765e-17j), (4.163336342344337e-17+1.5585811968653485j), (-1.0017346066809423+0j), (1.214306433183765e-17-0.5892556509887895j), (0.1178511301977579+3.469446951953614e-18j), (9.540979117872439e-18+0.04714045207910317j)]


#### 2. Using more term to correct parameter-shift rule

In [2]:
alpha = np.pi / 4
# beta = np.pi / 2
# gamma = np.pi / 3
lambdas = [-1, 0, 1]
# lambdas = [-3/2, -1/2, 1/2, 3/2]
# lambdas = [-2, -1, 0, 1, 2]
# lambdas = [-3, -2, -1, 1, 2, 3]
# lambdas = [-3, -2, -1, 0, 1, 2, 5]
delta_Malpha = base.calculate_Lambda_matrix(lambdas, alpha) - base.calculate_Lambda_matrix(lambdas, -alpha)
#delta_Mbeta = base.calculate_Lambda_matrix(lambdas, beta) - base.calculate_Lambda_matrix(lambdas, -beta)
#delta_Mgamma = base.calculate_Lambda_matrix(lambdas, gamma) - base.calculate_Lambda_matrix(lambdas, -gamma)
d1 = 1/2
d2 = (-np.sqrt(2) + 1) / 4
# T_alpha = upper_matrix(delta_Malpha)
# T_beta = upper_matrix(delta_Mbeta)
# T_gamma = upper_matrix(delta_Mgamma)


In [3]:
print(np.round(delta_Malpha, 3))
print(base.upper_matrix(delta_Malpha))

[[ 0.+0.j     0.-1.414j  0.+0.j   ]
 [ 0.+1.414j  0.+0.j    -0.-0.414j]
 [ 0.+0.j    -0.+0.414j  0.+0.j   ]]
[[-0.-0.41421356j]]


In [3]:
Ts = []
deltas = []
thetas = []
dim_d = 8 # int(len(lambdas)**2/4) - 1 
for i in range(0, dim_d):
    theta = np.random.uniform(0, 2*np.pi)
    delta = (base.calculate_Lambda_matrix(lambdas, theta) - base.calculate_Lambda_matrix(lambdas, -theta))
    thetas.append(theta)
    deltas.append(delta)
    Ts.append(base.upper_matrix(delta))

In [93]:
Ts = []
deltas = []
thetas = [np.pi/4, 3*np.pi/4]
dim_d = 2 # int(len(lambdas)**2/4) - 1 
for i in range(0, dim_d):
    delta = (base.calculate_Lambda_matrix(lambdas, thetas[i]) - base.calculate_Lambda_matrix(lambdas, -thetas[i]))
    deltas.append(delta)
    Ts.append(base.upper_matrix(delta))

In [4]:
deltas[0]

array([[0.+0.00000000e+00j, 0.-5.46355511e-02j, 0.+1.95068957e-18j,
        0.+4.40001528e-02j, 0.-2.71393464e-19j, 0.-5.86655241e-03j],
       [0.+5.46355511e-02j, 0.+0.00000000e+00j, 0.-1.06839958e-01j,
        0.+6.04239866e-18j, 0.+1.94250821e-02j, 0.+3.07196524e-19j],
       [0.-1.95068957e-18j, 0.+1.06839958e-01j, 0.+0.00000000e+00j,
        0.-8.60424096e-02j, 0.-1.62836079e-19j, 0.+1.14720580e-02j],
       [0.-4.40001528e-02j, 0.-6.04239866e-18j, 0.+8.60424096e-02j,
        0.+0.00000000e+00j, 0.-1.56437807e-02j, 0.-8.96206617e-19j],
       [0.+2.71393464e-19j, 0.-1.94250821e-02j, 0.+1.62836079e-19j,
        0.+1.56437807e-02j, 0.+0.00000000e+00j, 0.-2.08578956e-03j],
       [0.+5.86655241e-03j, 0.-3.07196524e-19j, 0.-1.14720580e-02j,
        0.+8.96206617e-19j, 0.+2.08578956e-03j, 0.+0.00000000e+00j]])

In [6]:
T = Ts[0]
for i in range(1, len(Ts)):
    T = np.hstack((T, Ts[i]))

In [7]:
from scipy.linalg import null_space

init_rcond = 1
while True:
    d = (null_space(T, rcond = init_rcond))
    if d.shape[1] != 1:
        init_rcond /= 10
    else:
        break

In [8]:
d

array([[-0.90685992-0.j        ],
       [-0.21133997-0.06283005j],
       [-0.20903059-0.0433079j ],
       [-0.02031613+0.04260863j],
       [ 0.04537332-0.15032986j],
       [-0.07713104+0.04085243j],
       [ 0.01210504+0.21342936j],
       [ 0.05520491-0.01315893j]])

In [9]:
thetas

[3.1298582023463513,
 4.3613686933384415,
 1.9659784833110965,
 4.830868311014382,
 2.8400820540315936,
 1.2211069784243804,
 2.9504379691722784,
 0.9880655511826192]

In [10]:
T @ d

array([[ 2.77555756e-17-2.77555756e-16j],
       [ 6.93889390e-18+2.08166817e-17j],
       [-1.94289029e-16+2.22044605e-16j],
       [ 3.46944695e-17-8.32667268e-17j],
       [-8.32667268e-17+2.77555756e-16j],
       [ 1.73472348e-17-3.46944695e-17j],
       [-2.42861287e-17+2.77555756e-17j],
       [-5.20417043e-18+1.12757026e-17j]])

In [11]:
sumMatrix = d[0] * deltas[0]
for i in range(1, len(Ts)):
    sumMatrix += d[i] * deltas[i]
print(np.round(sumMatrix, 3))

[[ 0.+0.j     0.-0.009j  0.-0.j    -0.-0.j    -0.+0.j     0.+0.j   ]
 [-0.+0.009j  0.+0.j    -0.+0.j     0.-0.j     0.-0.j     0.-0.j   ]
 [-0.+0.j     0.-0.j     0.+0.j    -0.+0.j     0.-0.j     0.-0.j   ]
 [ 0.+0.j    -0.+0.j     0.-0.j     0.+0.j    -0.+0.j    -0.+0.j   ]
 [ 0.-0.j    -0.+0.j    -0.+0.j     0.-0.j     0.+0.j    -0.+0.j   ]
 [-0.-0.j    -0.+0.j    -0.+0.j     0.-0.j     0.-0.j     0.+0.j   ]]


Theo công thức phải chia thêm hệ số (2j)

In [113]:
d_t = d / ((2j)*(-1.09+0.38j))

In [114]:
d_t

array([[ 0.42691009+1.76683978e-04j],
       [-0.07324619-3.03141781e-05j]])

d_t giống với kết quả của [Pennylane](https://docs.pennylane.ai/en/stable/code/api/pennylane.CRY.html)

In [115]:
(1 - np.sqrt(2)) / (4*np.sqrt(2))

-0.07322330470336313

In [91]:
sumMatrix = d_t[0] * deltas[0]
for i in range(1, len(Ts)):
    sumMatrix += d_t[i] * deltas[i]
print(np.round(sumMatrix, 3))

[[ 0.+0.j    -1.+0.001j  0.+0.j   ]
 [ 1.-0.001j  0.+0.j     0.-0.j   ]
 [ 0.+0.j    -0.+0.j     0.+0.j   ]]


In [12]:
alpha = np.pi / 4
beta = 3*np.pi / 4
lambdas = [-1, 0, 1]

delta_Malpha = base.calculate_Lambda_matrix(lambdas, alpha) - base.calculate_Lambda_matrix(lambdas, -alpha)
delta_Mbeta = base.calculate_Lambda_matrix(lambdas, beta) - base.calculate_Lambda_matrix(lambdas, -beta)

d1 = (np.sqrt(2) + 1)/(4*np.sqrt(2))
d2 = (-np.sqrt(2) + 1)/(4*np.sqrt(2))

print(d1*delta_Malpha + d2*delta_Mbeta)

[[0.+0.00000000e+00j 0.-5.00000000e-01j 0.+0.00000000e+00j]
 [0.+5.00000000e-01j 0.+0.00000000e+00j 0.+5.55111512e-17j]
 [0.+0.00000000e+00j 0.-5.55111512e-17j 0.+0.00000000e+00j]]
